### ISSUE TITLE
[Feature Request] Preset modes

### ISSUE THREAD

**Issue by JOHLC** [jcwillox/hass-template-climate#10]
I would use this to integrate sleep / eco / normal modes

Ref: https://developers.home-assistant.io/docs/core/entity/climate/#presets

A device can have different presets that it might want to show to the user. Common presets are "Away" or "Eco". There are a couple of built-in presets that will offer translations, but you're also allowed to add custom presets.

<html>
<body>

Name | Description
-- | --
ECO | Device is running an energy-saving mode
AWAY | Device is in away mode
BOOST | Device turn all valve full up
COMFORT | Device is in comfort mode
HOME | Device is in home mode
SLEEP | Device is prepared for sleep
ACTIVITY | Device is reacting to activity (e.g. movement sensors)

</body>
</html>

**Comment by ABCChrisJ** [comment]
Agreed, preset modes would be really nice to have.  They are the one thing I'm missing to be able to have my ideal setup, which is homekit for my ecobee thermostats, but still have presets available.

For what it's worth, at least with the ecobee thermostats (I don't know if all thermostats which support presets do this), there is a `preset_modes` attribute provided by the integration, so there should be a new preset_modes_template parameter to be able to provide the list of preset modes that are available, as well as set_preset_mode action to select one.

**Comment by Yiivgeny** [comment]
+1

**Comment by JOHLC** [comment]
Still interested in this, especially since it is getting hotter and hotter!

**Comment by JOHLC** [comment]
Found some info about presets in the developer docs: 
https://developers.home-assistant.io/docs/core/entity/climate/#presets

**Comment by siljelb** [comment]
+1 for this! I need it to create more functional climate entities for both my air handling unit and my bathroom thermostat.

**Comment by mow-jow** [comment]
Need ECO and BOOST 👍

**Comment by keniji** [comment]
+1.
I am using this integration and created a dummy climate entity. The real climate is controlled via an automation, not with the dummy climate. So if the `Preset modes` feature can be added, it will be very useful even if it is a dummy entry and has no ability to control the real climate.

**Comment by codingcatgirl** [comment]
Yep, this would be great to see!

**Comment by antro31** [comment]
+1

**Comment by klingbing** [comment]
+1, would lbe great to have this.

**Comment by Tamas-Toth-ebola** [comment]
@jcwillox +1 request for: please integrate PRESET handling if possible!

**Comment by chuckie007** [comment]
@jcwillox +1

Adding in the changes from PR #52 worked
