### ISSUE TITLE
[Feature Request] HVAC action

### ISSUE THREAD

**Issue by shift-del1** [jcwillox/hass-template-climate#12]
Can you please add a template for HVAC action (what is the climate doing at the moment, based on the current and the target temperature: heating, cooling, idle). This would be very important for the climate card in UI Lovelace Minimalist, especially my native climate integration is not providing this and I need to use a helper entity. Thank you.

**Comment by jcwillox** [comment]
I'm a little confused here, isn't the HVAC action just the current HVAC mode, if that's the case we already have the `hvac_mode_template` option.

**Comment by shift-del1** [comment]
> I'm a little confused here, isn't the HVAC action just the current HVAC mode, if that's the case we already have the `hvac_mode_template` option.

No, HVAC mode is for example Heat or Cool, HVAC action is limited to cooling, heating or idle. If HVAC mode is set to Cool, current temperature is 22°C, target temperatures is 24°C, HVAC action will be idle, because cooling is not needed. Thank you

**Comment by NdR91** [comment]
I agree with @shift-del1
Also an on/off template will be useful.

Currently, if the Climate is turned off by an external device (for example, the remote), the entity created by this integration won't be able to know it.

**Comment by bnapalm** [comment]
Agreed, this would be very useful.

**Comment by jcwillox** [comment]
Support for this was added in https://github.com/jcwillox/hass-template-climate/releases/tag/0.5.0
