### ISSUE TITLE
Cannot add to repository

### ISSUE THREAD

**Issue by sabixx** [jcwillox/hass-template-climate#30]
### The problem

Hi,

first of all many thanks for creating this. It looks like this would solve a lot of challenges.

Unfortunately, I'm failing to install this via HACS.

When I add the URL https://github.com/jcwillox/hass-template-climate as a custom repository I get the message:

<Theme jcwillox/hass-template-climate> Repository structure for 0.6.0 is not compliant. 

### What version of Template Climate has the issue?

0.6.0

### What version of Home Assistant are you running?

Home Assistant 2022.11.4 Supervisor 2022.11.2 Operating System 9.3 Frontend 20221108.0 - latest 

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```python3
not found anything in the logs.
```

### Additional information

I also tried to install it manual by copying the files but I get the message that I need to manually add it to configuration.yaml and I don't know what needs to go in there.

**Comment by sabixx** [comment]
found a log entry when manually adding the files to custom_components/climate_template/

Logger: homeassistant.setup
Source: setup.py:230
First occurred: 11:30:50 (1 occurrences)
Last logged: 11:30:50

Setup failed for custom integration climate_template: No setup or config entry setup function defined.

**Comment by jcwillox** [comment]
I think you might have added the repo as a theme instead of an integration, just check you selected the category as "integration" when adding it.

![image](https://user-images.githubusercontent.com/39120423/205475024-a909b0ad-485c-48a0-82fe-54ed5b46dd40.png)

**Comment by sabixx** [comment]
> I think you might have added the repo as a theme instead of an integration, just check you selected the category as "integration" when adding it.
> 
> ![image](https://user-images.githubusercontent.com/39120423/205475024-a909b0ad-485c-48a0-82fe-54ed5b46dd40.png)

oh.. I'm sorry. That's it. Thank a lot!

**Comment by jcwillox** [comment]
That's all good glad you got it working 👍
