### ISSUE TITLE
`None` `hvac_action` should be allowed

### ISSUE THREAD

**Issue by laszlojakab** [jcwillox/hass-template-climate#32]
### The problem

The `None` value is a valid `hvac_action` but the integration does not allow it. See the default value of `hvac_action` in developer docs:

https://developers.home-assistant.io/docs/core/entity/climate/#properties

### What type of installation are you running?

None

**Comment by purcell-lab** [comment]
This will be very useful for me when merged as I will be able to set the hvac_action based on the power consumption of the device.

For example when my HVAC is in Cool mode and my power consumption is above the baseload for the fan, I can set the Cooling mode, similar for Heat mode.
