### ISSUE TITLE
Fails after HA upgrade 

### ISSUE THREAD

**Issue by gr8er1mark** [jcwillox/hass-template-climate#4]
Thanks for your work on this I have been looking for something like this for sometime! I got it all setup and working yesterday.

Today I updated HA to version 2022.4.0 and got a config error in my configuration.yaml related to climate.climate_template (from memory I think that is what it said). I rolled back the HA update and everything is working fine again. Unfortunately I didn't copy the error message before rolling back 😕.  The message said something about 'FAN_HIGH' or maybe it was 'SPEED_HIGH' regarding fan settings either it wasn't recognised in the HA configuration. I don't use fan in my config personally it seemed to be pulling the error from the actual integrations setup.

**Comment by jcwillox** [comment]
Should be fixed now, and hopefully a bit more robust. I've published an actual versioned release [0.2.0](https://github.com/jcwillox/hass-template-climate/releases/tag/0.2.0) with the fix.

**Comment by gr8er1mark** [comment]
Thanks. Upgraded and all working perfectly 👍
