### ISSUE TITLE
turn_on/turn_off methods without setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by purcell-lab** [jcwillox/hass-template-climate#61]
### The problem

Home Assistant 2024.3 is currently in beta and is doing some more strict checking of climate devices and has detected an issue with this integration.

### What version of Template Climate has the issue?

0.6.1

### What version of Home Assistant are you running?

2024.3.b1

### What type of installation are you running?

Home Assistant Supervised

### Anything in the logs that might be useful for us?

```python3
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:361
integration: Climate (documentation, issues)
First occurred: 5:30:03 AM (3 occurrences)
Last logged: 5:32:51 AM

Entity climate.climate_master (<class 'custom_components.climate_template.climate.TemplateClimate'>) implements HVACMode(s): auto, off, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jcwillox/hass-template-climate/issues
```

**Comment by litinoveweedle** [comment]
Hello,

if you like, you can use my [forked repo](https://github.com/litinoveweedle/hass-template-climate), where I am merging multiple feature request with some of my own patches. ;-) The above error is patched there.

**Comment by SiriosDev** [comment]
just create a pr to this repo

**Comment by litinoveweedle** [comment]
Why should I? I am happy to maintain my fork, which has now more features, some of those were long PR in this repo but were never merged. There has to be two to dance. So thank you, but no thank you.

**Comment by SiriosDev** [comment]
Dunno, (for me) it doesn't seem the most elegant thing in the world to me to fork without even trying a merge, when the original repo is still maintained.

That doesn't mean I won't switch to your version which seems better. You seem sure you don't want to merge, which is the second most important thing after functions (not having to switch back, in a word stability)

**Comment by SiriosDev** [comment]
Dunno, (for me) it doesn't seem the most elegant thing in the world to me to fork without even trying a merge, when the original repo is still maintained.

That doesn't mean I won't switch to your version which seems better. You seem sure you don't want to merge, which is the second most important thing after functions (not having to switch back, in a word stability)

**Comment by sayam93** [comment]
I've created a PR to address this https://github.com/jcwillox/hass-template-climate/pull/82

Hopefully it gets reviewed and merged soon.

**Comment by sayam93** [comment]
> Dunno, (for me) it doesn't seem the most elegant thing in the world to me to fork without even trying a merge, when the original repo is still maintained.
> 
> That doesn't mean I won't switch to your version which seems better. You seem sure you don't want to merge, which is the second most important thing after functions (not having to switch back, in a word stability)

I've created a PR to address this https://github.com/jcwillox/hass-template-climate/pull/84

Hopefully it gets reviewed and merged soon.
