### ISSUE TITLE
implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by firstcolle** [jcwillox/hass-template-climate#76]
### The problem

warning in log

Entity climate.splitter_soggiorno_template (<class 'custom_components.climate_template.climate.TemplateClimate'>) implements HVACMode(s): auto, off, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jcwillox/hass-template-climate/issues

### What version of Template Climate has the issue?

0.8.0

### What version of Home Assistant are you running?

core-2024.10.4

### What type of installation are you running?

Home Assistant OS

### Anything in the logs that might be useful for us?

```python3
Entity climate.splitter_soggiorno_template (<class 'custom_components.climate_template.climate.TemplateClimate'>) implements HVACMode(s): auto, off, cool, heat, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/jcwillox/hass-template-climate/issues
```

**Comment by sayam93** [comment]
I've made a Pull Request to fix this.
https://github.com/jcwillox/hass-template-climate/pull/81

**Comment by sayam93** [comment]
I've added a PR to fix this https://github.com/jcwillox/hass-template-climate/pull/82

**Comment by firstcolle** [comment]
thanks, is there a new version to download for fix the issue?
