### ISSUE TITLE
Add support for heat_cool mode

### ISSUE THREAD

**Issue by cryptk** [jcwillox/hass-template-climate#8]
Hello,

I am attempting to use your integration to merge together the HomeKit Controller based integration and the Ecobee integration for my thermostats to work around some issues with the buggy HomeKit implementation in Ecobee thermostats.

One thing I have run into is the lack of support for the `heat_cool` HVAC mode along with it's associated `target_temp_high` and `target_temp_low` attributes.

Any chance these could be added?

**Comment by jcwillox** [comment]
Yep, this should be working in [0.4.0](https://github.com/jcwillox/hass-template-climate/releases/tag/0.4.0).

**Comment by cryptk** [comment]
Just updated, I'll give it a try

**Comment by cryptk** [comment]
Some quick testing and it seems to be working.  Thanks for the fast feature add!
